### ISSUE TITLE
Error logs: error:0406D06E:rsa and error:0906D06C:PEM

### ISSUE THREAD

**Issue by messalas** [nextcloud/announcementcenter#142]
Hello, 

I installed **announcementcenter** and I posted an announcement. However, none user received the email about the announcement (it is enabled in settings).

In the logs (from the page) I am getting:

> [notifications] Fatal: error:0406D06E:rsa routines:RSA_padding_add_PKCS1_type_2:data too large for key size at 2019-02-18T08:30:04 +00:00
> 
> [notifications] Fatal: error:0906D06C:PEM routines:PEM_read_bio:no start line at 2019-02-8T08:30:04 +00:00
> 

thanks

```
### Server configuration
Nextcloud version : 15.0.4
Operating system and version: Ubuntu 16.04
Apache : Apache/2.4.18 (Ubuntu)
PHP version : PHP 7.0.32-0ubuntu0.16.04.1

http://example.com/index.php/settings/integrity/failed => No errors have been found.
```

**Comment by nickvergessen** [comment]
The errors should be unrelated.

Emails are sent via a cron job, because it can take a while for large instances. Please make sure you cron is set up correctly and/or executed often enough in case of the web cron:

https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/background_jobs_configuration.html
