### ISSUE TITLE
Mail addresses within announcement messages are not displayed on /apps/announcementcenter/

### ISSUE THREAD

**Issue by DanScharon** [nextcloud/announcementcenter#172]
### Steps to reproduce
1. Publish an announcement text that contains an email address
2. Go to the announcements page. The email address is not rendered in the browser
3. Look at your notifications. The email address is shown there
4. Look at your notifications in your sync client. The email address is shown there

### Expected behaviour
Announcement texts should be rendered displaying an email address.

### Actual behaviour
Announcement texts on the announcement page do not render email addresses.

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** PostgreSQL 11

**PHP version:** 7.3

**Nextcloud version:** 16.0.6

**Where did you install Nextcloud from:** Manually

**Comment by Luticus** [comment]
I've noticed this behavior as well. I just want to add that this oddly used to work fine, though I'm not sure how many versions back it was. I hadn't tested it in a while.

**Comment by alexanderdd** [comment]
can confirm for NC 18.0.3 and Announcement center 3.7.0. 

@nickvergessen in my opinion this is a bug, not an enhancement. The product does not work as expected, and there is no warning that email addresses will be deleted.

Btw Hyperlinks work fine so it cannot be connected to the idea of "making announcements more secure by deleting any links".

I need this because I use announcements from the admin for regular users, and I want them to be able to contact me. If I put my Email like "mail AT tld DOT com" they will be very confused.

**Comment by nickvergessen** [comment]
I guess the problem is somewhere here or in the rest of this method:
https://github.com/nextcloud/announcementcenter/blob/master/js/script.js#L231-L261

**Comment by DanScharon** [comment]
unfortunately I have to reopen this issue. It is still not fixed.
Nextcloud 19.0.8
Announcement Center 3.8.1

**Comment by nickvergessen** [comment]
It was only  added in 3.9.1+ so you need to update to Nextcloud 20 first
