### ISSUE TITLE
allow announcements to be emailed to users

### ISSUE THREAD

**Issue by jon-tlmi** [nextcloud/announcementcenter#65]
It would be awesome if an announcement could be emailed to any users who have entered their email address into their profile. Perhaps it could be under Advanced options? A check box would do it.

**Reason**: This suits multi-user environments, esp where some non-technical members only have the client running and rarely if ever visit the web interface.

Example use cases:
1. Quota changes
2. Hey Grandma, I moved your Soundgarden collection to /ancient/
3. Hey everyone, please check our the revised Where do I store..? guide.

**Comment by yohan33** [comment]
Hello,

Has anyone found a solution to send email to user groups when creating an announcement on NextCloud with the Announcment Center application?

thank you in advance,
Have a good day

**Comment by jancborchardt** [comment]
As discussed in https://github.com/nextcloud/announcementcenter/issues/115, this should be the default and not just an option. :)

**Comment by nickvergessen** [comment]
Urgh, I just implemented this, but it is colliding with #74 
Because the Markdown markup is there plaintext in the emails, which is kind of odd too.
Work is in #140

**Comment by rmeissn** [comment]
@nickvergessen said that he implemented in 3.3.1 (#65) to show the title of the announcement in the notification e-mail. At least with a newly set up Nextcloud 15 and installed Announcement Center 3.4.1, there is just a generic notification about an announcement without any title, description or link.

In my opinion it would be best to have e-mails with (decreasing usefulness):
* title + description + link to the announcement
* title + link to the announcement
* link to the announcement

There are also some libraries available that are able to convert markdown to plaintext (search for "markdown to plaintext"). In my opinion it's better to see some title and text (even not perfectly formatted) instead of none.

**Comment by fsch2** [comment]
I run NC 23.0.0 and the announcement center only sends out generic mail notifications. They do not include the title and also not the content. How can I send at least the title of the announcement? If I read this issue correct, this should already be possible.

**Comment by fsch2** [comment]
Let me correct myself: the title is indeed contained in the notification mail.

**Comment by fsch2** [comment]
Thanks for implementing the change with the announcement titles in the mail notification.

I also think, that it is better to have raw markdown text in the notification mail than no text at all.

**Comment by zeitalexgithub** [comment]
Any updates? Is now possible to include text of announcement in E-Mail? May be by editing templates or so?

**Comment by wokawoka** [comment]
My users never receive the e-mail notification from an admin announcement.
It's a mystery, I was not able to understand where the problem lies. Cron is working fine and all the other notifications works perfectly.
Any hint?

**Comment by mejo-** [comment]
I took another try to get this implemented. See #467
