### ISSUE TITLE
Basic text formatting

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/announcementcenter#74]
Maybe even Markdown support?
Minimum:
- Bold,
- Underline,
- Text indent
- Links (like href in html)

**Comment by walterheisenberg** [comment]
[NC/dashboard](https://github.com/nextcloud/dashboard
) announcements has some basic text formatting:

**Comment by Schmuuu** [comment]
Adding screenshots/ pictures (which are stored on the Nextcloud server) would be awesome as well.

How can I add a bounty to this issue? For me personally this is by far the most needed feature in Nextcloud.

**Comment by Schmuuu** [comment]
Hi @nickvergessen 

Will there be a new version, which contains these features, soon? I'd like to use these features asap and would prefer an update of the app via the NC app store, because I'm not very familiar with building apps myself and actually don't know how to do that when I just pull the branch with markdown support.
Any help or a new version is very welcome.

And by the way: thank you very much for your time and effort you put into this app!

**Comment by nickvergessen** [comment]
My idea is to add email support to ( #65 ) and then release.
Thursday is reserved for non-scheduled work, and this is high on the list for that. I hope to finish it this thursday and would then do a release at night.

**Comment by Schmuuu** [comment]
I see. Yeah, that's perfect! I'll be patient then ;)
Thanks a lot!

**Comment by nickvergessen** [comment]
Released: https://apps.nextcloud.com/apps/announcementcenter/releases?platform=15#15
