### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by zeidanbm** [nextcloud/announcementcenter#88]
```**Operating system**:
ubuntu 16.04
**Web server:**
apache 2.*
**Database:**
mysql mariadb
**PHP version:**
7.0
**Nextcloud version:**
12.0
**Where did you install Nextcloud from:**
downloaded from nextcloud.com

**List of activated apps:**
notification app, activity app, announcment center app

**Nextcloud configuration:**
out of the box
```
**This is not an issue, I just need help on somethings related to announcment center app.**

I was trying to integrate a real time push notification into the code either using a node server or a third party server like pusher and had to go through the code. I'm pretty new to nextcloud so bare with me if I miss understood something. This is about the connection built in the announcement center under the BackgroundJob.php file which is Queued and the Notifier.php that maps your anncounement to the notification app. So, the application(announcment center) needs to wait for the cron job to run(by the server mostly) in order to send the announcment we created to the notification app (i.e pretty much save it in the database under the oc_notificaiton table) and notification app is set to run an api call every 30 sec ;which can be reduced by changing 'pollInterval' in the code; to get it's notificaitons  (i.e whatever under oc_notificaiton table) and display them under the bell icon for the users to see.

Questions:
Is the queue the problem here? as queued jobs will have to wait for the cron job to run. So Can we by pass the queue and make the connection to notificaiton app happen directly after sending the announcment?

**Comment by nickvergessen** [comment]
Well the cron should be executed every 5 minutes.

For smaller instances we could immediately do the activities and notifications. The problem is, that for bigger instances it might take too long and will timeout (while you are trying to post the announcement).
That's why it was moved to a background job.

Just make sure you run the background jobs via system cron instead of ajax and it should be fine.

See https://docs.nextcloud.com/server/12/admin_manual/configuration_server/background_jobs_configuration.html for more information.
